Mldb 1967 fetch fct refactoring
mldbai/mldb pull request #702
Opened 2016-10-03 17:15 UTC by FinchPowers

2016-10-03 17:26 UTC, mailletf commented
Je pense qu'il fallait juste renomer la built-in function à fetch, mais garder le type de la user function à fetcher. Genre une instance de la fonction de type fetcher s'appel fetch.

2016-10-03 17:43 UTC, jeremybarnes commented on container_files/public_html/doc/builtin/functions/Fetch.md
> -# Fetcher Function
That should still be "Fetcher" (which is a noun).

2016-10-03 17:43 UTC, jeremybarnes commented on container_files/public_html/doc/builtin/functions/Fetch.md
> +![](%%config function fetch)
Still fetcher

2016-10-03 17:47 UTC, jeremybarnes requested changes
1.  The "fetcher" function class stays fetcher, only the builtin function gets renamed.
2.  The "fetch" builtin function should be moved to fetcher.cc (not put in its own file), and should operate by creating its own Fetcher function on bind and calling that on apply().  No need to refactor the code out and create a third class; it's unnecessary.

2016-10-03 17:47 UTC, jeremybarnes commented on container_files/public_html/doc/builtin/sql/ValueExpression.md
> +#### `fetch(str)`
This one should be fetch :)

2016-10-03 17:47 UTC, jeremybarnes commented on plugins/fetcher.cc
> -        try {
This file shouldn't change at all.

2016-10-03 18:48 UTC, FinchPowers commented
Updated.

2016-10-04 01:29 UTC, co-dh commented
I still have access to mldb github, can you please remove me.

2016-10-04 01:56 UTC, jraby commented
@co-dh This repo is public, everyone has read access.

2016-10-11 13:41 UTC, jeremybarnes commented
Mich there is a much cleaner way to do it.  Do you mind holding off until I get back?

2016-10-11 13:44 UTC, FinchPowers commented
No problem. As long as it doesn't rot.

2016-12-13 18:35 UTC, FinchPowers commented
It looks like it has rotten. :p

2017-01-18 15:04 UTC, guyd commented on container_files/public_html/doc/builtin/sql/ValueExpression.md
> +default version of [function fetch](../functions/Fetch.md.html). It returns
Le fichier n'a pas changé de nom.

2017-01-18 15:05 UTC, guyd commented on container_files/tutorials/Tensorflow Image Recognition Tutorial.ipynb
>      "print mldb.put('/v1/functions/fetch', {\n",
Dans le tutorial, j'utiliserais le built-in `fetch`.

2017-01-18 15:06 UTC, guyd commented on plugins/fetcher.cc
> +static RegisterBuiltin registerFetcherFunction(fetcher, "fetch");
je garderais l'ancien nom aussi pour la compatibilité.

2026-01-15 01:19 UTC, closed without merging